name: Generate Top Languages

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create generated folder
        run: mkdir -p generated

      - name: Generate Languages (Light - Lavender)
        run: |
          sleep 5
          curl -L -H "User-Agent: github-actions" \
          "https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api/top-langs/?username=aaryamahajan919&layout=compact&hide_border=true&bg_color=ffffff&title_color=a855f7&text_color=a855f7&cache_seconds=86400" \
          -o generated/langs-light.svg

      - name: Generate Languages (Dark)
        run: |
          sleep 5
          curl -L -H "User-Agent: github-actions" \
          "https://github-readme-stats-git-masterrstaa-rickstaa.vercel.app/api/top-langs/?username=aaryamahajan919&layout=compact&theme=tokyonight&hide_border=true&cache_seconds=86400" \
          -o generated/langs-dark.svg

      - name: Commit files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add generated/langs-*.svg
          git commit -m "update langs" || echo "no changes"
          git push
